baseURL: ""
languageCode: en-us
title: Mujtaba's Portfolio
theme: PaperMod

menu:
  main:
  - identifier: blog
    name: Blog
    title: Blog
    url: /blog/
    weight: 10
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 20
  - identifier: projects
    name: Projects
    title: Projects
    url: /projects/
    weight: 30

params:
    profileMode:
        enabled: true
        title: "Welcome to my eportfolio!"
        subtitle: "I am Mujtaba, a programmer that loves exploring"
        imageUrl: "images/my-face.jpg"
        imageTitle: "my picture"
        imageWidth: 256
        imageHeight: 256

    socialIcons:
        - name: "github"
          url: "https://github.com/igreat"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/mujtaba-al-ajmi-b256b9242/"
        - name: "email"
          url: "mailto:mujtaba.alajmi13.20@takatufscholars.om"
        
markup:
  goldmark:
    renderer:
      unsafe: true