baseURL: https://igreat.github.io/
languageCode: en-us
title: Mujtaba
theme: PaperMod

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 10
  - identifier: videos
    name: Videos
    title: Videos
    url: /videos/
    weight: 20
  - identifier: resume
    name: Resume
    title: Resume
    url: /resume/
    weight: 30
  - identifier: blog
    name: Blog
    title: Blog
    url: /blog/
    weight: 40
  - identifier: projects
    name: Projects
    title: Projects
    url: /projects/
    weight: 50

params:
    profileMode:
        enabled: true
        title: "Welcome!"
        subtitle: "I am Mujtaba, a programmer that loves exploring"
        imageUrl: "images/my-face-informal.jpeg"
        imageTitle: "my picture"
        imageWidth: 256
        imageHeight: 256

    socialIcons:
        - name: "github"
          url: "https://github.com/igreat"
        - name: "youtube"
          url: "https://www.youtube.com/channel/UC16BYekiN_0telZ2z_WgtDQ"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/mujtaba-al-ajmi-b256b9242/"
        - name: "email"
          url: "mailto:mujtaba.alajmi13.20@takatufscholars.om"
        
markup:
  goldmark:
    renderer:
      unsafe: true